on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # actions/checkout

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for SonarQube

      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci

      - run: npm run pipeline

      - uses: sonarsource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for PR metadata
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
