on:
  push:

env:
  NODE_VERSION: 20

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - run: npm ci
      - run: npm run pipeline
